# Generated by Django 6.0.4 on 2026-05-02 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="品种名称")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="品种编码"
                    ),
                ),
                (
                    "planting_location",
                    models.CharField(max_length=255, verbose_name="定植地点"),
                ),
                ("planting_date", models.DateField(verbose_name="定植时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "产品信息",
                "verbose_name_plural": "产品信息",
                "db_table": "product",
            },
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "图片"), ("video", "视频")],
                        max_length=20,
                        verbose_name="媒体类型",
                    ),
                ),
                ("url", models.CharField(max_length=500, verbose_name="媒体URL")),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="媒体标题"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="媒体描述"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序顺序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="traceability.product",
                        verbose_name="关联产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "多媒体信息",
                "verbose_name_plural": "多媒体信息",
                "db_table": "media",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="HarvestQuality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("harvest_start_date", models.DateField(verbose_name="采收起始时间")),
                ("harvest_end_date", models.DateField(verbose_name="采收终止时间")),
                (
                    "sugar_content",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="糖度(Brix)"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="单果重量(克)"
                    ),
                ),
                ("taste", models.CharField(max_length=255, verbose_name="口感描述")),
                (
                    "suitable_crowd",
                    models.CharField(max_length=255, verbose_name="适应人群"),
                ),
                ("quality_summary", models.TextField(verbose_name="品质小结")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="harvest_quality",
                        to="traceability.product",
                        verbose_name="关联产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "采收质量信息",
                "verbose_name_plural": "采收质量信息",
                "db_table": "harvest_quality",
            },
        ),
    ]
